<<<<<<< Updated upstream
# Generated by Django 3.2.dev20210102203948 on 2021-03-17 01:52
=======
# Generated by Django 3.2.dev20210102203948 on 2021-03-17 01:57
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
