# Generated by Django 3.0.1 on 2021-03-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
