# Generated by Django 3.0.1 on 2021-03-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='child',
        ),
    ]
