# Generated by Django 3.2.dev20210102203948 on 2021-03-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210318_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
