# Generated by Django 3.2.dev20210102203948 on 2021-03-25 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_child_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='max_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activities',
            name='reg_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='activities',
            name='reg_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='activities',
            name='age_group_old',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='activities',
            name='age_group_young',
            field=models.IntegerField(default=0),
        ),
    ]
