# Generated by Django 3.2.dev20210102203948 on 2021-03-25 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210325_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 9, 37, 383959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 9, 37, 382962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activities',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
