# Generated by Django 3.2.dev20210102203948 on 2021-03-25 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210325_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='reg_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 16, 49, 736682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 16, 49, 736682, tzinfo=utc)),
        ),
    ]
