# Generated by Django 3.2.dev20210102203948 on 2021-03-28 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210325_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='reg_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 13, 9, 43, 723613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 13, 9, 43, 723613, tzinfo=utc)),
        ),
    ]
