# Generated by Django 3.2.dev20210102203948 on 2021-03-28 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210328_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='activity_list',
        ),
        migrations.AddField(
            model_name='activities',
            name='registrant',
            field=models.ManyToManyField(to='users.Child'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 16, 55, 51, 559898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 16, 55, 51, 559898, tzinfo=utc)),
        ),
    ]
