# Generated by Django 3.0.1 on 2021-03-30 21:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210330_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 21, 53, 32, 83571, tzinfo=utc), verbose_name='Registration End Time'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 21, 53, 32, 83530, tzinfo=utc), verbose_name='Registration Start Time'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='start_date',
            field=models.DateField(),
        ),
    ]
