# Generated by Django 3.0.1 on 2021-03-30 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210330_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='end_date',
            field=models.DateField(verbose_name='End Date (YYYY/MM/DD)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 21, 56, 35, 813769, tzinfo=utc), verbose_name='Registration End Time'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 21, 56, 35, 813735, tzinfo=utc), verbose_name='Registration Start Time'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='start_date',
            field=models.DateField(verbose_name='Start Date (YYYY/MM/DD)'),
        ),
    ]
