# Generated by Django 3.1.7 on 2021-03-31 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210330_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='registrant',
        ),
        migrations.AddField(
            model_name='child',
            name='activities',
            field=models.ManyToManyField(to='users.Activities'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 18, 4, 58, 752290, tzinfo=utc), verbose_name='Registration End Time'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 18, 4, 58, 752290, tzinfo=utc), verbose_name='Registration Start Time'),
        ),
    ]
