# Generated by Django 3.1.7 on 2021-03-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210331_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='reg_end',
            field=models.DateField(verbose_name='Registration End Date (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='reg_start',
            field=models.DateField(verbose_name='Registration Start Date (YYYY-MM-DD)'),
        ),
    ]
